hadoop:

  blueprint: "hdp-aramcheck-cluster"
  default_password: "admin"
  host_groups:
    -
      hosts:
        -
          fqdn: "ip-172-31-0-099.eu-central-1.compute.internal"
        -
          fqdn: "ip-172-31-0-100.eu-central-1.compute.internal"
        -
          fqdn: "ip-172-31-0-101.eu-central-1.compute.internal"
      name: "host_group_master_2"
    -
      hosts:
        -
          fqdn: "ip-172-31-0-106.eu-central-1.compute.internal"
      name: "host_group_master_3"
    -
      hosts:
        -
          fqdn: "ip-172-31-0-107.eu-central-1.compute.internal"
      name: "host_group_slave_1"
    -
      hosts:
        -
          fqdn: "ip-172-31-0-104.eu-central-1.compute.internal"
      name: "host_group_slave_2"
    -
      hosts:
        -
          fqdn: "ip-172-31-0-105.eu-central-1.compute.internal"
      name: "host_group_client_1"